version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /app
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/perceptify
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - mongo

volumes:
  mongo_data:
